remote_theme: alshedivat/al-folio@main
plugins:
  - jekyll-remote-theme

title: "vehicle-classification"
description: "A Jekyll site for vehicle classification project"

author:
  name: "Taiob Md Ridwan"
  email: "tridwan.ds25@gmail.com"